# management/commands/add_java_questions.py

from django.core.management.base import BaseCommand
from app1.models import Basic_JavaQuestion

class Command(BaseCommand):
    help = 'Add sample Java questions to the database'

    def handle(self, *args, **kwargs):
        questions = [
            {
                'question_text': 'What is a class in Java?',
                'option_a': 'A blueprint for creating objects',
                'option_b': 'A function',
                'option_c': 'A variable',
                'option_d': 'None of the above',
                'correct_option': 'A',
            },
            {
                'question_text': 'What is inheritance in Java?',
                'option_a': 'A process of defining a new class based on an existing class',
                'option_b': 'A way to create multiple objects',
                'option_c': 'A function',
                'option_d': 'None of the above',
                'correct_option': 'A',
            },
            # Add more questions here...
            {
        'question_text': 'What is inheritance in Java?',
        'option_a': 'A process of defining a new class based on an existing class',
        'option_b': 'A way to create multiple objects',
        'option_c': 'A function',
        'option_d': 'None of the above',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of the following is not a Java feature?',
        'option_a': 'Object-oriented',
        'option_b': 'Use of pointers',
        'option_c': 'Portable',
        'option_d': 'Dynamic and Extensible',
        'correct_option': 'B',
    },
    {
        'question_text': 'What is the default value of the local variables?',
        'option_a': 'null',
        'option_b': '0',
        'option_c': 'Depends on the data type',
        'option_d': 'No default value for local variables',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of these cannot be used for a variable name in Java?',
        'option_a': 'identifier & keyword',
        'option_b': 'identifier',
        'option_c': 'keyword',
        'option_d': 'none of the mentioned',
        'correct_option': 'C',
    },
    {
        'question_text': 'What is the size of a Char in Java?',
        'option_a': '4 bits',
        'option_b': '7 bits',
        'option_c': '8 bits',
        'option_d': '16 bits',
        'correct_option': 'D',
    },
    {
        'question_text': 'What is a correct syntax to output "Hello World" in Java?',
        'option_a': 'System.out.println("Hello World");',
        'option_b': 'echo("Hello World");',
        'option_c': 'print ("Hello World");',
        'option_d': 'Console.WriteLine("Hello World");',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which data type is used to create a variable that should store text?',
        'option_a': 'String',
        'option_b': 'myString',
        'option_c': 'Txt',
        'option_d': 'string',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which method can be used to find the length of a string?',
        'option_a': 'getLength()',
        'option_b': 'len()',
        'option_c': 'length()',
        'option_d': 'getSize()',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which keyword is used to create a class in Java?',
        'option_a': 'class',
        'option_b': 'Class',
        'option_c': 'myClass',
        'option_d': 'className',
        'correct_option': 'A',
    },
    {
        'question_text': 'How do you create a method in Java?',
        'option_a': 'methodName[]',
        'option_b': 'methodName()',
        'option_c': 'methodName.',
        'option_d': 'methodName{}',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which statement is used to stop a loop?',
        'option_a': 'break',
        'option_b': 'stop',
        'option_c': 'return',
        'option_d': 'exit',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which keyword is used to return a value inside a method?',
        'option_a': 'return',
        'option_b': 'get',
        'option_c': 'break',
        'option_d': 'null',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which keyword is used to import a package in Java?',
        'option_a': 'import',
        'option_b': 'package',
        'option_c': 'include',
        'option_d': 'using',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which operator is used to add together two values?',
        'option_a': '*',
        'option_b': '+',
        'option_c': '/',
        'option_d': '-',
        'correct_option': 'B',
    },
    {
        'question_text': 'What is the correct way to create an array?',
        'option_a': 'int[] arr = new int[5];',
        'option_b': 'int arr[] = new int[5];',
        'option_c': 'int arr[5] = new int[];',
        'option_d': 'int[] arr = int[5] new;',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which method must be defined to be called in a thread?',
        'option_a': 'start()',
        'option_b': 'run()',
        'option_c': 'stop()',
        'option_d': 'main()',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which of the following is a superclass of every class in Java?',
        'option_a': 'Object',
        'option_b': 'String',
        'option_c': 'Main',
        'option_d': 'Class',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is returned by the operator "&"?',
        'option_a': 'Integer',
        'option_b': 'Character',
        'option_c': 'Boolean',
        'option_d': 'Float',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which of the following is used to create an object?',
        'option_a': 'class',
        'option_b': 'method',
        'option_c': 'constructor',
        'option_d': 'constant',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which method is used to find the square root of a number?',
        'option_a': 'sqrt()',
        'option_b': 'power()',
        'option_c': 'sqr()',
        'option_d': 'root()',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which package is used for standard input and output operations?',
        'option_a': 'java.util',
        'option_b': 'java.lang',
        'option_c': 'java.io',
        'option_d': 'java.net',
        'correct_option': 'C',
    },
    {
        'question_text': 'What is the default value of the boolean data type?',
        'option_a': 'true',
        'option_b': 'false',
        'option_c': '0',
        'option_d': 'null',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which method is called when an object is created?',
        'option_a': 'constructor',
        'option_b': 'new()',
        'option_c': 'create()',
        'option_d': 'instantiate()',
        'correct_option': 'A',
    },
    {
        'question_text': 'What is the size of an int variable in Java?',
        'option_a': '4 bytes',
        'option_b': '8 bytes',
        'option_c': '2 bytes',
        'option_d': '1 byte',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of the following is used to handle exceptions in Java?',
        'option_a': 'try-catch',
        'option_b': 'throw-catch',
        'option_c': 'try-throw',
        'option_d': 'catch-throw',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is not a bitwise operator?',
        'option_a': '&',
        'option_b': '|',
        'option_c': '!=',
        'option_d': '^',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which of the following is the correct way to declare a variable in Java?',
        'option_a': 'int number;',
        'option_b': 'int number = 5',
        'option_c': 'int number 5;',
        'option_d': 'number int;',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of the following is not a valid access modifier?',
        'option_a': 'public',
        'option_b': 'private',
        'option_c': 'protected',
        'option_d': 'internal',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of the following is used to terminate a statement in Java?',
        'option_a': '.',
        'option_b': '!',
        'option_c': ';',
        'option_d': ':',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which of the following loops will execute at least once?',
        'option_a': 'for',
        'option_b': 'while',
        'option_c': 'do-while',
        'option_d': 'none',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which of these data types is not primitive?',
        'option_a': 'int',
        'option_b': 'float',
        'option_c': 'boolean',
        'option_d': 'String',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of these is used to define an abstract class?',
        'option_a': 'abstract',
        'option_b': 'interface',
        'option_c': 'extends',
        'option_d': 'implements',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is not a valid keyword?',
        'option_a': 'class',
        'option_b': 'extends',
        'option_c': 'implements',
        'option_d': 'define',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of these methods is used to set the position of a file pointer?',
        'option_a': 'seek()',
        'option_b': 'move()',
        'option_c': 'set()',
        'option_d': 'point()',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these keywords is used to define a package in Java?',
        'option_a': 'package',
        'option_b': 'import',
        'option_c': 'define',
        'option_d': 'pack',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is used to invoke a method?',
        'option_a': '.',
        'option_b': '!',
        'option_c': ':',
        'option_d': '->',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these cannot be used to create an object?',
        'option_a': 'new',
        'option_b': 'clone',
        'option_c': 'constructor',
        'option_d': 'delete',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of these is a valid variable name?',
        'option_a': '1variable',
        'option_b': 'variable1',
        'option_c': 'variable-1',
        'option_d': 'variable 1',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which of these is not a valid identifier?',
        'option_a': 'class',
        'option_b': 'myClass',
        'option_c': 'my_class',
        'option_d': 'MyClass',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is a valid keyword?',
        'option_a': 'goto',
        'option_b': 'switch',
        'option_c': 'null',
        'option_d': 'true',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which of these is used to find the length of an array?',
        'option_a': 'length',
        'option_b': 'size',
        'option_c': 'length()',
        'option_d': 'size()',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is used to throw an exception?',
        'option_a': 'catch',
        'option_b': 'throw',
        'option_c': 'throws',
        'option_d': 'try',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which of these is not a valid exception?',
        'option_a': 'IOException',
        'option_b': 'SQLException',
        'option_c': 'InputMismatchException',
        'option_d': 'NumberException',
        'correct_option': 'D',
    },
    {
        'question_text': 'Which of these is used to create an object?',
        'option_a': 'new',
        'option_b': 'class',
        'option_c': 'method',
        'option_d': 'constructor',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is used to access a class?',
        'option_a': '.',
        'option_b': ':',
        'option_c': '->',
        'option_d': '!',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is used to handle exceptions?',
        'option_a': 'try-catch',
        'option_b': 'throw-catch',
        'option_c': 'try-throw',
        'option_d': 'catch-throw',
        'correct_option': 'A',
    },
    {
        'question_text': 'Which of these is used to import a package?',
        'option_a': 'package',
        'option_b': 'import',
        'option_c': 'include',
        'option_d': 'using',
        'correct_option': 'B',
    },
    {
        'question_text': 'Which of these is used to declare a constant?',
        'option_a': 'const',
        'option_b': 'static',
        'option_c': 'final',
        'option_d': 'constant',
        'correct_option': 'C',
    },
    {
        'question_text': 'Which of these is used to return a value from a method?',
        'option_a': 'return',
        'option_b': 'get',
        'option_c': 'exit',
        'option_d': 'end',
        'correct_option': 'A',
    }
        ]

        for question in questions:
            Basic_JavaQuestion.objects.create(**question)

        self.stdout.write(self.style.SUCCESS('Successfully added sample questions'))
