# Generated by Django 5.0.7 on 2024-07-31 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advance_Java_Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Advance_java_test_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Advance_Python_Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Advance_python_test_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Basic_java_test_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Basic_JavaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                ("correct_option", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Basic_python_test_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("fees_amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("certificate_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("details", models.TextField()),
                ("batch_number", models.IntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Intern_Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Java_Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="JoinDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("join_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Python_Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Python_otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="random_otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disclaimer", models.BooleanField(default=False)),
                (
                    "cert",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record_advance_java_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_advance_java_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disclaimer", models.BooleanField(default=False)),
                (
                    "cert",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record_advance_python_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_advance_python_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disclaimer", models.BooleanField(default=False)),
                (
                    "cert",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record_basic_java_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_basic_python_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_intern_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("disclaimer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record_intern_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disclaimer", models.BooleanField(default=False)),
                (
                    "cert",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record_java",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passed_out_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("working", "Currently Working"),
                            ("unemployed", "Currently Unemployed"),
                            ("still_studying", "Currently Still Studying"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="nil", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disclaimer", models.BooleanField(default=False)),
                (
                    "cert",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
                (
                    "attempt",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (4, "4")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record_Landingpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "student_batch",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppLink_community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppLink_java",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppLink_python",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag",
                    models.IntegerField(
                        choices=[(-1, "-1"), (0, "0"), (1, "1"), (2, "2")], default=0
                    ),
                ),
                ("batch_number", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
