name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_PASSWORD: ${{ secrets.PA_PASSWORD }}
      run: |
        curl -u $PA_USERNAME:$PA_PASSWORD \
             -X POST \
             -d "command=python manage.py migrate" \
             https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/yourappname/reload/
