name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Adjust this to your main branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_USERNAME: ${{ secrets.GuruTechDev}}
        PYTHONANYWHERE_PASSWORD: ${{ secrets.gurudev@123 }}
      run: |
        curl -u $GuruTechDev:$gurudev@123 \
             -X POST \
             -F "file=@deploy.sh" \
             https://www.pythonanywhere.com/api/v0/user/$.GuruTechDev/webapps/GuruTechDev.pythonanywhere.com/reload/
